export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as Features } from './Features';
export { default as Stats } from './Stats';
export { default as TechStack } from './TechStack';
export { default as Pricing } from './Pricing';
export { default as CTA } from './CTA';
export { default as Footer } from './Footer';
export { default as CodeEditor } from './CodeEditor';
